export const Constants = {
  AUTH_REQUEST:'AUTH_REQUEST',
  AUTH_SUCCESS:'AUTH_SUCCESS',
  AUTH_FAIL:'AUTH_FAIL',
  USER_FETCH_REQUEST:'USER_FETCH_REQUEST',
  USER_FETCH_SUCCESS:'USER_FETCH_SUCCESS',
  USER_FETCH_FAIL:'USER_FETCH_FAIL',
  PLAYLISTS_FETCH_REQUEST:'PLAYLISTS_FETCH_REQUEST',
  PLAYLISTS_FETCH_SUCCESS:'PLAYLISTS_FETCH_SUCCESS',
  PLAYLISTS_FETCH_FAIL:'PLAYLISTS_FETCH_FAIL',
  TRACKS_FETCH_REQUEST:'TRACKS_FETCH_REQUEST',
  TRACKS_FETCH_SUCCESS:'TRACKS_FETCH_SUCCESS',
  TRACKS_FETCH_FAIL:'TRACKS_FETCH_FAIL',
};
